### PR TITLE
Lightspeed; adapt to Obsidian v0.15.0

### LINKED ISSUE #35: [Feature request] Lightspeed.nvim-similar execution for "Jump to Anywhere"
Hello mrjackphil! Thank you for creating such an awesome plugin! It provides an even more fluent Vim experience.

## Introduction

In short, [Lightspeed.nvim](https://github.com/ggandor/lightspeed.nvim) is a motion plugin very similar to [vim-easymotion](https://github.com/easymotion/vim-easymotion). The reason for a Lightspeed-similar execution is to remove much visual clutter. 

With the current "Jump to Anywhere" implementation, if I want to, say, jump to `consectetur`, this is the screen after triggering `activate-jump-to-anywhere`:

screenshot-2022-03-31-19-53-56

This is the screen for Lightspeed-simliar implementation:
screenshot-2022-03-31-19-54-23

Current implementation:

Trigger `activate-jump-to-anywhere` ->  all words are parsed for tags -> press the two keys on tag to jump to desired word

Lightspeed-similar implementation:

Trigger `activate-jump-to-anywhere` -> press first two characters of desired word -> provides tags that matches `jumpToAnywhereRegex` for jump

## Having trouble implementing

I've looked into `handleJumpToRegex` in `main.ts`. The crust of the matter is that, **how do I capture two extra keypress sequence after triggering `activate-jump-to-anywhere`**?

```js
    handleJumpToRegex = () => {
        const { app, settings: { letters } } = this
        const currentView = app.workspace.activeLeaf.view;
        const mode = this.getMode(currentView);

        ****************************************
        let capturedTwoKeys = "" // e.g., "ow"
        let twoKeysRegex = "\b" + capturedTwoKeys; // replaced `jumpToAnywhereRegex` since it needs to be generated on-the-fly when we trigger `activate-jump-to-anywhere`.
        ****************************************
        
        switch (mode) {
            case VIEW_MODE.LIVE_PREVIEW:
                const cm6Editor: EditorView = (<{ editor?: { cm: EditorView } }>currentView).editor.cm;
                const livePreviewLinks = new LivePreviewRegexProcessor(cm6Editor, letters, **twoKeysRegex**).init();
                this.markPlugin.setLinks(livePreviewLinks);
                this.app.workspace.updateOptions();
                this.handleActions(livePreviewLinks, cm6Editor);
                break;
            case VIEW_MODE.PREVIEW:
                break;
            /* OMITTED */
            default:
                break;
        }
    }
```

I tried adding an `addEventListener`: `document.addEventListener('keydown', (event) => console.log(event.key));`, but it's not captured in Normal mode, only in Insert mode.

I'm also confused as to where I should look for reference: [obsidian.d.ts](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts) or [codemirror](https://codemirror.net/6/docs/guide/#extension)? 

Any help is much appreciated. Thank you!

### PR DESCRIPTION
**Pull request by kometenstaub**
Closes #35, #38, based on https://github.com/mrjackphil/obsidian-jump-to-link/issues/35#issuecomment-1085905668.

cc @kohane27, @chrisgrieser

- implements lightspeed
- separates cm6 plugin instances
- adapts jump to link and anywhere to Obsidian v0.15.0

I added a gif, but it would make sense if you link it, because then the absolute URL is not connected to this fork.

### CODE REVIEW

**Comment by kohane27** [comment]
@kometenstaub 

Thank you for taking it up to implement it and acknowledging the original implementation in the code:)

I tried this morning:

https://user-images.githubusercontent.com/57322459/173939703-a704a2e5-6845-44e8-b2f4-5aa95c492906.mp4

To reproduce:

1. press `s` to trigger
2. press `si` to try to jump to "simple"
3. no label appeared and the text stays grayed out. Had to restart Obsidian

I will investigate this issue later: not sure if it's my Obsidian (conflict with other plugins).

Another issue I always have with the original code is that, if I cancel a jump, all the text stays grayed out. I guess this is related to how the event loop of JS works. Not sure how to do it however.

**Comment by kometenstaub** [comment]
The current code only works with Obsidian v0.15+ which is currently in insider.

The first two commits should still work with 0.14.15, although they don't contain some bug fixes.

**Comment by kometenstaub** [comment]
> Another issue I always have with the original code is that, if I cancel a jump, all the text stays grayed out. I guess this is related to how the event loop of JS works. Not sure how to do it however.

Yes, I also noticed that. I'll think on it.

**Comment by kohane27** [comment]
> The current code only works with Obsidian v0.15+ which is currently in insider.
> 
> The first two commits should still work with 0.14.15, although they don't contain some bug fixes.

I completely wasn't aware that I'm on v0.14.15. I'll give it another go when I can update to v0.15. Sorry about that :confused:

**Comment by kometenstaub** [comment]
@kohane27 It just needed the line that resets the colour for <kbd>Esc</kbd>: https://github.com/mrjackphil/obsidian-jump-to-link/pull/39/commits/7ac6fc81f65d078104ed7dbff8dbc7026e99522f

**Comment by kometenstaub** [comment]
https://user-images.githubusercontent.com/83140328/173943136-87632877-94ab-4089-9cd3-5b4b4f98e7b3.mp4

That's v0.4.2 which contains the <kbd>Esc</kbd> fix.

**Comment by tadashi-aikawa** [comment]
Hi, @kometenstaub. Thank you for your excellent work!

I was looking for a solution that enables it to work correctly in popup windows. So I tried to build your forked repository, and it worked perfectly 👍 

Also, I like [Two key highlighting of easymotion](https://github.com/easymotion/vim-easymotion#two-key-highlighting), and you already have implemented a similar feature!!

If possible, it would be great if you implement the following two features :)

1. case-insensitive match (Input `so` can match with `So`)
2. Jump to immediately if there is only one matching

Best regards. Thanks again😄

**Comment by kometenstaub** [comment]
> If possible, it would be great if you implement the following two features :)
> 
> 1. case-insensitive match (Input so can match with So 

That could be a global setting. 
https://github.com/kometenstaub/obsidian-jump-to-link/blob/7ac6fc81f65d078104ed7dbff8dbc7026e99522f/src/utils/regexp.ts#L4

> 2. Jump to immediately if there is only one matching 

That's also doable, just need to check whether the length is 1.
https://github.com/kometenstaub/obsidian-jump-to-link/blob/7ac6fc81f65d078104ed7dbff8dbc7026e99522f/src/main.ts#L195

---

By the way, I have a minimal implementation of vim-sneak as a jsfile script I use with the vimrc plugin. I'll publish that in the coming days along with some other vim plugins/scripts I've written.

**Comment by tadashi-aikawa** [comment]
@kometenstaub 
Thank you for your quick reply :)

> That could be a global setting.
> https://github.com/kometenstaub/obsidian-jump-to-link/blob/7ac6fc81f65d078104ed7dbff8dbc7026e99522f/src/utils/regexp.ts#L4

Could you tell me the correct settings? I don't know what to set.

image

image

image

**Comment by kometenstaub** [comment]
I meant that I want to make it a global setting.

I'll have to think a bit on the implementation because jump to anywhere and lightspeed share code and it would need to be independant of the jump to anywhere regex.

**Comment by kometenstaub** [comment]
@tadashi-aikawa I took care of 1).

Implementing 2) is more difficult than I thought, because just adding it to the current implementation isn't quite possible without changing the architecture of how linkhints are handled.

This would make more sense as a separate PR after this one is merged.

**Comment by tadashi-aikawa** [comment]
> I took care of 1).

Thanks, @kometenstaub! I rebuilt and enabled it, but not working as expected. Did I make a mistake? 🤔

image

**Comment by kometenstaub** [comment]
The option is about case-*sensitivity*. You enabled it, which means it is case-*sensitive*, instead of case-***in***sensitive.

**Comment by tadashi-aikawa** [comment]
Ah.. sorry 😅  I disabled it, and it worked perfectly 👍 Thank you!

**Pull request merged**
