### PR TITLE
Add JumpToAnywhere Regex based editor navigation

### PR DESCRIPTION
**Pull request by jsonMartin**
I was looking for a good way to navigate Obsidian via Keyboard, and this plugin was the closest I found. `Jump-to-link` Works great for links, but I was also wanting something closer to `vim-easymotion` for editing text. 

This Pull Request adds keyboard-based navigation features to text in the editor, so it can act more like `vim-easymotion`'s "Jump To Anywhere" functionality; this feature complements link navigation already present in the plugin. 

Related to this Issue: https://github.com/mrjackphil/obsidian-jump-to-link/issues/9

jumptoanywhere

### How to use Jump to Anywhere (Editor Navigation)
- Use the command pallete, or press the hotkey (`Ctrl + ;` by default) to instantly jump to any word on the page!
- Jump to Anywhere is a RegEx based navigation feature, similar to [`vim-easymotion`](https://github.com/easymotion/vim-easymotion).
- Jump to Anywhere works both in regular editor mode, and in VIM mode!
- Custom RegEx can be configured to user preference
- Default configuration adds a label on words 3 characters or greater: [Regex: `\b\w{3,}\b`]

---
So far, I've tested it and it works on small to medium size documents, but needs improvement on large documents - I've listed the issues & possible fixes below. But for now, I just wanted to get the ball rolling and share what I've built so far 😊

## Known Issues
- JumpToAnywhere Regex performance issues on large documents (runs out of letters and results in slow performance)
  - Possible Fixes
    - Raise number of possible combinations to 3 letters
    - Contain text selection only to visible lines

### CODE REVIEW

**Comment by mrjackphil** [comment]
Thanks for the pull request.

I was planning to show links only for visible lines and start showing links relative from the active lines. This should help with performance and usability. 

But that was in a 2020 and I still didn't do this. Let me revisit the code base and do fix some general issues before adding new functionality. 

I'll try to do it this week.

**Comment by jsonMartin** [comment]
> 
> 
> Thanks for the pull request.
> 
> I was planning to show links only for visible lines and start showing links relative from the active lines. This should help with performance and usability.
> 
> But that was in a 2020 and I still didn't do this. Let me revisit the code base and do fix some general issues before adding new functionality.
> 
> I'll try to do it this week.

Hey @mrjackphil, nice! That would also fix the performance issue for JumpToAnywhere on large documents, and should ensure that there is no need for more than 2 character jump labels.

After you find time to make the fixes, I'll rebase my PR off your new version and test to see how it works. Thanks!

**Comment by mrjackphil** [comment]
Also, while I remember, the name "Jump to anywhere" might be misleading because people might expect to jump to any pane/ui element and such.

There were request #17 which makes me feel what people might expect more functionality from the feature called in that way 😁

**Comment by mrjackphil** [comment]
@jsonMartin So in the latest release, we just showing links only for visible parts which should help with performance. 
Please, rebase the PR, and sorry for what you need to do this :)

**Comment by jsonMartin** [comment]
Nice, thanks @mrjackphil ! I am about to head out for the weekend, but will work on integrating your newest fixes next week 👍

Also, I just used the "Jump To Anywhere" name because that's what `vim-easymotion` calls it, but if you have another name you would recommend instead for the feature I'm agnostic to what it's called 😎

**Comment by tallguyjenks** [comment]
PLEASE. I've wanted `Easy Motion` functionality from this plugin for AGES lol great work @jsonMartin !! 🚀

**Comment by mrjackphil** [comment]
@jsonMartin Tried to bring more specific name for the feature but didn't find any. Let's stick with "Jump to anywhere" and we'll see how it goes.

**Comment by jsonMartin** [comment]
Hey @mrjackphil , just finished rebasing off your newest version and integrating your improvements into the PR. 

It works much better now! The performance is faster on large documents, and it doesn't run out of letters as it did before (although I did add more letters to the new configuration option in my settings to ensure I have enough jumping labels available for documents with lots of text matches). Tested on a few documents and everything seems to be working as intended.

**Comment by mrjackphil** [comment]
@jsonMartin Merged. Fixed bug where default Regexp didn't work because JS wants to escape `\` symbol.

**Comment by jsonMartin** [comment]
Perfect. Thanks!

**Pull request merged**
